[package]
name = "DitherRS"
version = "0.1.0"
edition = "2024"

[dependencies]
async-std = "1.13.1"
dither-lib = "0.1.2"
image = "0.25.6"
slint = "1.11.0"
tokio = { version = "1.45.1", features = ["full"] }

[build-dependencies]
slint-build = "1.11.0"
