import { Button, Slider } from "std-widgets.slint";

export component AppWindow inherits Window {
    in-out property <string> message: "Hello World";
    in-out property <image> image;
    in-out property <image> image2;

    callback dither(int);

    min-width: 1000px;
    min-height: 1000px;
    title: "Hello world";

    HorizontalLayout {
        VerticalLayout {
            Text {
                text: message;
            }

            Slider {
                minimum: 1;
                maximum: 7;
                value: 3;
                step: 1;
                released(value) => {
                    root.dither(value);
                }
            }

            //Button {
            //    text: "Hello World";
            //    clicked => {
            //        root.dither();
            //    }
            //}
        }

        VerticalLayout {
            width: 50%;
            HorizontalLayout {
                Image {
                    source: image;
                }

                Image {
                    source: image2;
                }
            }
        }
    }
}
